### ISSUE TITLE
[Bug]: Unable to interpolate static replicas using Mia-Platform double mustache notazion

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/mlp#83]
### What version or versions you have tested?

1.2.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### What did you expect to happen?

I expect the following command to be successfully executed with a interpolated value for static replicas:
`mlp kustomize "${OVERLAY_PATH}" -o "${DESTINATION_PATH}/kustomize-output.yaml"`

### What happened instead?

I set a environment variable on the Mia-Platform static replicas value of a service:
`{{NGINX_REPLICAS}}`

The resulting deployment file is the following:
```
spec:
  replicas: {{NGINX_REPLICAS}}
```

The following command fails:
`mlp kustomize "${OVERLAY_PATH}" -o "${DESTINATION_PATH}/kustomize-output.yaml"`

Following a screenshot of the error:
<img width="776" alt="Screenshot 2023-06-20 at 14 40 09" src="https://github.com/mia-platform/mlp/assets/28152586/7fb6cba9-05c4-43d5-96d0-f51ce4032204">

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by silversoul93** [comment]
Hi guys,
do you have any update on this bug?

**Comment by davidebianchi** [comment]
Hi! I investigated on this issue. The raised error is from kustomize, which raise this error because you try to build a kubernetes resource with a string (`{{NGINX_REPLICAS}}`) inside the replicas field, which must be a number.

To fix this, you should interpolate the files (with mlp interpolate) before the kustomize build. 
I close this bug, since it is not a mlp bug. Reopen it if something is not clear.
